apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-1 # Changed to match what you created
  namespace: default
  annotations:
    # kubernetes.io/ingress.class: "gce" # Old annotation
    kubernetes.io/ingress.class: "gce"
    # ingress.gcp.kubernetes.io/pre-shared-cert: "mcrt-484191be-39be-4ec0-a558-f774994dc498" # <-- ADD THE CERTIFICATE ID HERE
    # cert-manager.io/issue-temporary-certificate: "true"
    # acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  # ingressClassName: "gce" # New way to specify Ingress class
  defaultBackend:
    service:
      name: frontend-service
      port:
        number: 80
  rules:
    # - host: thefrontmangames.com
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
  # tls:
  #   - hosts:
  #       - thefrontmangames.com